version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neugpt-backend
    ports:
      - "223:3000"
    env_file:
      - ./backend/.env
    networks:
      - neugpt-network
    restart: unless-stopped

  # Frontend service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neugpt-frontend
    ports:
      - "222:80"
    depends_on:
      - backend
    networks:
      - neugpt-network
    restart: unless-stopped

networks:
  neugpt-network:
    driver: bridge 