services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neugpt-backend
    ports:
      - "222:3000"
    env_file:
      - ./backend/.env
    # volumes: for local development
    #   - ./backend:/app
    networks:
      - neugpt-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neugpt-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    # volumes: for local development
    #   - ./frontend:/usr/share/nginx/html
    networks:
      - neugpt-network
    restart: unless-stopped

networks:
  neugpt-network:
    driver: bridge 